fallitems:
  - enchanted_golden_apple
  - enchanted_golden_apple
  - ender_pearl
  - golden_apple
  - golden_apple
  - golden_apple
  - diamond_block
  - emerald_block
  - gold_block
  - iron_block
  - iron_block
  - iron_block
  - enchanting_table
  - enchanting_table
  - obsidian
  - obsidian
  - diamond
  - diamond
  - gold_ingot
  - gold_ingot
  - enchanted_book
  - enchanted_book
  - enchanted_book
  - enchanted_book
  - potion
  - potion
  - potion
  - potion
  - emerald
  - emerald
  - netherite_ingot
  - anvil
  - experience_bottle
  - experience_bottle
  - experience_bottle
  - bookshelf
fallitemscount:
  - 1
  - 1
  - 3
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 16
  - 16
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 16
  - 16
  - 16
  - 16
enchantslist:
  - sharpness
  - infinity
  - flame
  - unbreaking
  - power
  - punch
  - efficiency
  - knockback
  - protection
peffects:
  - speed
  - increase_damage
  - fire_resistance
  - jump
  - levitation
  - fast_digging
